# Generated by Django 4.0 on 2021-12-18 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_commentcrm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_df',
            new_name='order_dt',
        ),
    ]
